version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    user: "101:101"
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - clickhouse